cleanup:
  Annotations:
    helm.sh/hook: pre-delete
    helm.sh/hook-delete-policy: hook-succeeded
  Args:
  - --cleanup
controllerbuild:
  enabled: true
expose:
  Annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-delete-policy: hook-succeeded
  Args:
  - --v
  - 4
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-delete-policy: hook-succeeded
  config:
    domain: us.g.csanchez.beescloud.com
    exposer: Ingress
    http: "false"
    pathmode: ""
    tlsacme: "true"
jenkins:
  enabled: false
  servers:
    ghe: []
    gitea: []
    global:
      envvars:
        TILLER_NAMESPACE: kube-system
pipelinesecrets:
  dockerconfig: ""
prow:
  hmactoken: ""
  oauthtoken: ""
  user: ""
